#!/bin/bash

_ROOT="$(dirname "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"

source "$_ROOT/.env"

declare -r cmd="${1}"

case "$cmd" in
  db-reset)
    psql << SQL
DROP DATABASE IF EXISTS $DB_NAME;
DROP USER IF EXISTS $DB_USER;

CREATE USER $DB_USER WITH ENCRYPTED PASSWORD '$DB_PASSWORD';
CREATE DATABASE $DB_NAME WITH OWNER $DB_USER;
SQL
    ;;
  db-seed)
    psql "postgresql://$DB_USER:$DB_PASSWORD@localhost/$DB_NAME?sslmode=require" < "$_ROOT/db/test.sql"
    ;;
  *)
    echo "Invalid cmd" >&2
    exit 1
    ;;
esac
